# Generated by Django 4.2.4 on 2023-12-19 12:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0002_alter_product_options_product_discount_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='image',
            field=models.ImageField(default='/products/default.png', upload_to='products/products/%Y/%m/%d', verbose_name='Изображение'),
        ),
    ]
